### ISSUE TITLE
why was PBR included?

### ISSUE THREAD

**Issue by mreinstein** [rledrin/WebGPU-Bloom#2]
I get that HDR helps with better looking bloom, but why is  PBR in here too?  It doesn't seem to be related to bloom.

Great repo by the way!  Seems like a pretty decent implementation of the ~blur~ bloom method described in the call of duty presentation.

**Comment by rledrin** [comment]
Hi !
I mainly included PBR because i wanted to see how it worked and emissive materials comes form PBR to my knowledge.
I believe that you can manage to make some bloom without PBR though but I think that it's not the "main" way to bloom.

**Comment by mreinstein** [comment]
It might be that I just misunderstand, but it seems like as soon as the `emissive intensity` is >= `2.0` there is no impact of the PBR settings on bloom.  Via the exposed sliders there doesn't seem to be any way to see both PBR and bloom effects. 

Is there some set of slider values that demonstrate both PBR _and_ bloom at the same time?  

Thanks again!

**Comment by mreinstein** [comment]
Said differently, when bloom is even marginally visible, changing any of the PBR settings doesn't seem to have any influence on the visible output.

**Comment by mreinstein** [comment]
btw I hope these questions don't come off as sounding hostile.   I'm genuinely curious about the approach taken, and trying to figure out why PBR is implemented.  

Ultimately I'm trying to develop good looking bloom with as simple an implementation as possible, and hoping that maybe the PBR portions are not truly needed.

**Comment by rledrin** [comment]
Sorry I just don't have much time, my implementation of PBR isn't really good and yes you can render some bloom without it, in the end you just need HDR (+ tone mapping to go back to LDR) and some texture/color with higher value than your bloom threshold (usually 1.0). And don't forget the gamma correction (I think i did it wrong in this repo).
Have nice day and feel free to ask me any other question you migth have

**Comment by mreinstein** [comment]
Thanks for your time!  I'm looking forward to poking at this repo some more, and maybe spend some time making it work in the context of a web browser.
