### ISSUE TITLE
bug in bloom shader?

### ISSUE THREAD

**Issue by mreinstein** [rledrin/WebGPU-Bloom#3]
This line: https://github.com/rledrin/WebGPU-Bloom/blob/main/assets/shaders/bloom.wgsl#L135

```rust
if (global_invocation_id.x <= u32(imgSize.x) && global_invocation_id.x <= u32(imgSize.x)) {
```

This appears to be a duplicate guard against `imgSize.x`.  Maybe instead you meant to check the `imgSize.y` property in one of these checks instead?

**Comment by rledrin** [comment]
Hi
it indeed is an error, it should be:
```rust
if (global_invocation_id.x <= u32(imgSize.x) && global_invocation_id.y <= u32(imgSize.y)) {
```
in some cases, there might be more "compute invocation" than pixels in the texture so we might want to guard it this way
